[mypy]
python_version = 3.10
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
ignore_missing_imports = True

# Exclude test files
exclude = (^test_.*\.py$|^inspect_.*\.py$)

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True
